services:
- type: pserv
  name: elasticsearch-yente
  env: docker
  dockerfilePath: ./Dockerfile.elasticsearch
  plan: standard
  disk:
    name: esdata
    mountPath: /usr/share/elasticsearch/data
    sizeGB: 10
  autoDeploy: false # so ES does not restart on a push to this repository.
  envVars:
  - key: node.name
    value: index
  - key: cluster.name
    value: opensanctions-index
  - key: discovery.type
    value: single-node
  - key: bootstrap.memory_lock
    value: true
  - key: xpack.security.enabled
    value: false
  - key: ES_JAVA_OPTS
    value: "-Xms1g -Xmx1g"

- type: pserv
  name: yente
  env: docker
  dockerfilePath: ./Dockerfile.yente
  plan: standard
  autoDeploy: false
  envVars:
    - key: YENTE_ELASTICSEARCH_URL
      value: http://elasticsearch-yente:9200
    - key: YENTE_STATEMENT_API
      value: false
    - key: YENTE_UPDATE_TOKEN
      value: yenteupdate
