services:
- type: pserv
  name: elasticsearch-yente
  env: docker
  dockerfilePath: ./Dockerfile.elasticsearch
  plan: standard
  disk:
    name: esdata
    mountPath: /usr/share/elasticsearch/data
    sizeGB: 10
  autoDeploy: false # so ES does not restart on a push to this repository.
  envVars:
  - key: node.name
    value: index
  - key: cluster.name
    value: opensanctions-index
  - key: discovery.type
    value: single-node
  - key: bootstrap.memory_lock
    value: true
  - key: xpack.security.enabled
    value: false
  - key: ES_JAVA_OPTS
    value: "-Xms1g -Xmx1g"

- type: pserv
  name: yente
  env: docker
  dockerfilePath: ./Dockerfile.yente
  plan: standard
  # TODO hopefully at some point Render will support a placeholder with the connection string including protocol
  # or allower for concatenation / interpolation with placeholder env vars
  # Until then we have to interpolate and override the start command
  startCommand: 'YENTE_ELASTICSEARCH_URL="http://${YENTE_ELASTICSEARCH_HOSTPORT}" yente serve'
  envVars:
    - key: YENTE_ELASTICSEARCH_HOSTPORT
      fromService:
        type: pserv
        name: elasticsearch-yente
        property: hostport
    - key: YENTE_STATEMENT_API
      sync: false
    - key: YENTE_UPDATE_TOKEN
      generateValue: true
